language: julia

julia:
  - 1.0
  - nightly

os:
  - linux
  - osx

coveralls: true

notifications:
  email: false

before_script:
  - export PATH=$HOME/.local/bin:$PATH

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'using Pkg; Pkg.test(coverage=true)'
