language: julia

julia:
  - 1.0
  - 1.1
  - nightly

matrix:
  allow_failures:
  - julia: nightly

os:
  - linux
  - osx

notifications:
  email: false

branches:
  only:
  - master
  - /release-.*/
  - /v(\d+)\.(\d+)\.(\d+)/

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("ReadOnlyArrays")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())';
  - julia -e 'using Pkg; cd(Pkg.dir("ReadOnlyArrays")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
